[package]
name = "cwos"
version = "0.1.0"
edition = "2021"

[dependencies]
# todo: set actual version numbers

# STD Only:
dirs = "*"

# STD Variations:
anyhow = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"

# No STD:
# ...
